services:
    _defaults:
        # make all services accessible directly from container
        public: true

    # Register our grid definition factory
    demogrid.grid.order_grid_definition_factory:
        class: 'DemoGrid\Grid\OrderTunnelGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
        arguments:
            - "@=service('router').generate('admin_common_reset_search', {'controller': 'ordertunnel', 'action': 'index'})"
            - "@=service('router').generate('demogrid_admin_index')"
        public: true

    # Register our query builder
    demogrid.grid.order_query_builder:
        class: 'DemoGrid\Grid\OrderTunnelQueryBuilder'
        parent: 'prestashop.core.grid.abstract_query_builder'
        arguments:
            - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
            - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
        public: true

    # Configure grid data provider to use our query builder that we registered above
    demogrid.grid.order_data_factory:
        class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
        arguments:
            - '@demogrid.grid.order_query_builder'
            - '@prestashop.core.hook.dispatcher'
            - '@prestashop.core.grid.query.doctrine_query_parser'
            - 'ordertunnel'

    # Configure grid factory which will use our grid definition factory and data provider services
    demogrid.grid.order_grid_factory:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
            - '@demogrid.grid.order_grid_definition_factory' # our grid definition factory service
            - '@demogrid.grid.order_data_factory'           # our data provider service
            - '@prestashop.core.grid.filter.form_factory'                            # core service needed by grid factory
            - '@prestashop.core.hook.dispatcher'   



